version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r deployment_package.zip lambda_function.py
artifacts:
  type: zip
  paths:
    - '*'
